version: "3.7"
services: 
    app2:
        build: ./app2
        ports: 
            - "8000:8000"
    app3:
        build: ./app3
        ports: 
            - "8001:8000"
    app4:
        build: ./app4
        depends_on: 
            - app2
            - app3
        ports: 
            - "8002:8000"
    app1:
        build: ./app1
        depends_on: 
            - app2
            - app3
            - app4
            - database
        ports: 
            - "80:8000"
        environment:
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_URI: ${DATABASE_URI}
            DBUser: ${DBUser}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            DBserv: ${DBserv}
        command: bash -c './chkDB.sh && gunicorn --workers=4 --bind=0.0.0.0:8000 app:app'
    database:
        image: mysql:5.7
        volumes:
            - "mydb:/var/lib/mysql"
        container_name: mysql
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: prizes
volumes:
    mydb:
