apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: prize
  name: prize
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prize
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: prize
    spec:
      containers:
      - args:
        - bash
        - -c
        - ./chkDB.sh && gunicorn --workers=4 --bind=0.0.0.0:8000 app:app
        env:
        - name: DATABASE_URI
        - name: DBUser
        - name: DBserv
        - name: MYSQL_ROOT_PASSWORD
        - name: SECRET_KEY
        image: elsahib/app1
        imagePullPolicy: ""
        name: prize
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
