apiVersion: apps/v1
kind: Deployment
metadata:
  name: prize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prize
  template:
    metadata:
      labels:
        app: prize
    spec:
      containers:
      - args:
        - bash
        - -c
        - ./chkDB.sh && gunicorn --workers=4 --bind=0.0.0.0:8000 app:app
        env:
          - name: DATABASE_URI
            value: {{DATABASE_URI}}
          - name: DBUser
            value: {{DBUser}}
          - name: DBserv
            value: {{DBserv}}
          - name: MYSQL_ROOT_PASSWORD
            value: {{MYSQL_ROOT_PASSWORD}}
          - name: SECRET_KEY
            value: {{SECRET_KEY}}
        image: elsahib/app1
        name: prize
        ports:
        - containerPort: 8000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: prize
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8000
  selector:
    app: prize
  type: LoadBalancer
