apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: prize
  name: prize
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8000
  selector:
    io.kompose.service: prize
  type: LoadBalancer
status:
  loadBalancer: {}
