apiVersion: apps/v1
kind: Deployment
metadata:
  name: przgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: przgen
  template:
    metadata:
      labels:
        app: przgen
    spec:
      containers:
      - image: elsahib/app4
        name: przgen
        ports:
        - containerPort: 8000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: przgen
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 8000
  selector:
    app: przgen

