apiVersion: apps/v1
kind: Deployment
metadata:
  name: txtgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: txtgen
  template:
    metadata:
      labels:
        app: txtgen
    spec:
      containers:
      - image: elsahib/app2
        name: txtgen
        ports:
        - containerPort: 8000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: txtgen
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    app: txtgen
